### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by kobrin666** [codyprashant/vfs-autobot#1]
Hi. Can you write FAQ for this program? Thanks

**Comment by codyprashant** [comment]
Yes it will be added. I just started this program so will be adding in few days. But please feel free to ask me if you have any question

**Comment by kobrin666** [comment]
> Yes it will be added. I just started this program so will be adding in few days. But please feel free to ask me if you have any question

we have link https://row2.vfsglobal.com/PolandBelarus-Appointment/Account/RegisteredLogin?q=shSA0YnE4pLF9Xzwon/x/ASnHZRMROGDyz5YljrTPrmD7weWKDzHm/9+x4kyou3T7EbygDK+7ECJT8O+dWpxGw==
is it possible to run this script on this site? and will it work?

**Comment by codyprashant** [comment]
Yes, it will work Currently it's designed for India -the Netherlands only. But if you want I can make it work.

Please let me know if you really need it.

**Comment by kobrin666** [comment]
> Yes, it will work Currently it's designed for India -the Netherlands only. But if you want I can make it work.
> 
> Please let me know if you really need it.

yes. im really need it asap. thanks

**Comment by codyprashant** [comment]
Hi @kobrin666, I have created new program with everything to run dynamically. Please visit this program [vfs-autobot-docker](https://github.com/codyprashant/vfs-autobot-docker-public/tree/master) . For any further questions, please reach out to the mentioned program.

**Comment by kobrin666** [comment]
> Hi @kobrin666, I have created new program with everything to run dynamically. Please visit this program [vfs-autobot-docker](https://github.com/codyprashant/vfs-autobot-docker-public/tree/master) . For any further questions, please reach out to the mentioned program.

can you add an example .env file to the project? I don’t understand a little how to create it and what data to enter. Thanks

**Comment by codyprashant** [comment]
@kobrin666 Are you a developer? I am attaching a sample env file there. If still has doubts, please reach out to me at prashant.gurukul6893@gmail.com

**Comment by codyprashant** [comment]
I am closing this program here. Please reach out to me on the [vfs-autobot-docker](https://github.com/codyprashant/vfs-autobot-docker-public/tree/master)., if you have any questions
